// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uueidupzdfzukwduimks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1ZWlkdXB6ZGZ6dWt3ZHVpbWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NTExMzAsImV4cCI6MjA3MjQyNzEzMH0._5SGHtyh04CFzDzRd6XLBU1bS7eeHCFiye9wQK2MwEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});